# Generated by Django 2.1.3 on 2019-01-31 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ViewOnRoad', '0002_auto_20190131_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
