# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-12 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ViewOnRoad', '0003_uploadfile_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
