# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-23 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ViewOnRoad', '0005_auto_20190218_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='longway_uploadfile_model',
            name='file',
            field=models.FileField(default='settings.MEDIA_ROOT/uploads/GMH_logo.png', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='roadview_uploadfile_model',
            name='file',
            field=models.FileField(default='settings.MEDIA_ROOT/uploads/GMH_logo.png', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='storyonroad_uploadfile_model',
            name='file',
            field=models.FileField(default='settings.MEDIA_ROOT/uploads/GMH_logo.png', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to='uploads'),
        ),
    ]
