# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-03 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ViewOnRoad', '0009_auto_20190301_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='question_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(default='settings.MEDIA_ROOT/uploads/GMH_logo.png', upload_to='uploads/')),
                ('text', models.TextField()),
            ],
        ),
    ]
